In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

file_path = 'Data MoMo.xlsx'
xls = pd.ExcelFile(file_path)
df1 = pd.read_excel(xls, sheet_name=xls.sheet_names[0])
df2 = pd.read_excel(xls, sheet_name=xls.sheet_names[1])
df3 = pd.read_excel(xls, sheet_name=xls.sheet_names[2])

print("Sheet 1:")
print(df1)
print("\nSheet 2:")
print(df2)
print("\nSheet 3:")
print(df3)

Sheet 1:
        user_id    order_id        Date   Amount  Merchant_id Purchase_status
0      21269588  4169517626  2020-01-01   10,000           13             NaN
1      28097592  4170276686  2020-01-01   20,000           13             NaN
2      47435144  4166729310  2020-01-01   10,000           12             NaN
3      29080935  4174460303  2020-01-01   10,000           13             NaN
4      14591075  4168216749  2020-01-01   10,000           12             NaN
...         ...         ...         ...      ...          ...             ...
13490  54337200  8720390921  2020-12-31   20,000           12             NaN
13491  59931360  8718580146  2020-12-31  100,000           12             NaN
13492  46156488  8717515352  2020-12-31   20,000           12             NaN
13493  35858614  8716668316  2020-12-31   10,000           12             NaN
13494  49335467  8710511927  2020-12-31   10,000           12             NaN

[13495 rows x 6 columns]

Sheet 2:
  Merchant_name  Merchant_id  Rate_pct
0       Viettel           12         2
1      Mobifone           13         3
2     Vinaphone           14         4
3  Vietnamobile           15         4
4       Gmobile           16         4

Sheet 3:
        User_id First_tran_date      Location       Age  Gender
0      41654498      2018-05-02          HCMC  33_to_37    MALE
1      51276281      2019-12-08  Other Cities   unknown    MALE
2      49152375      2019-12-20  Other Cities  23_to_27    MALE
3       5971050      2019-08-01          HCMC  28_to_32    MALE
4      48134464      2019-08-23  Other Cities  18_to_22  FEMALE
...         ...             ...           ...       ...     ...
13423  39810630      2018-03-19  Other Cities  28_to_32     Nam
13424  47628375      2019-09-05          HCMC  28_to_32  female
13425  46334970      2019-04-23  Other Cities   unknown    male
13426  50760533      2019-11-13  Other Cities  18_to_22      Ná»¯
13427  44818205      2019-03-05          HCMC  18_to_22     Nam

[13428 rows x 5 columns]

In [ ]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(13495, 6)
(5, 3)
(13428, 5)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13495 entries, 0 to 13494
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          13495 non-null  int64
 1   order_id         13495 non-null  int64
 2   Date             13495 non-null  object
 3   Amount           13495 non-null  object
 4   Merchant_id      13495 non-null  int64
 5   Purchase_status  2235 non-null   object
dtypes: int64(3), object(3)
memory usage: 632.7+ KB

In [ ]:
df1['Amount'] = df1['Amount'].str.replace(',', '').astype(float)

In [ ]:
def convert_date(date):
    try:
        return pd.to_datetime(date, format='%Y-%m-%d')
    except ValueError:
        return pd.to_datetime(date, format='%d/%m/%Y')

df1['Date'] = df1['Date'].apply(convert_date)
df1['Date'] = df1['Date'].dt.strftime('%Y-%m-%d')

print(df1)

        user_id    order_id        Date    Amount  Merchant_id Purchase_status
0      21269588  4169517626  2020-01-01   10000.0           13             NaN
1      28097592  4170276686  2020-01-01   20000.0           13             NaN
2      47435144  4166729310  2020-01-01   10000.0           12             NaN
3      29080935  4174460303  2020-01-01   10000.0           13             NaN
4      14591075  4168216749  2020-01-01   10000.0           12             NaN
...         ...         ...         ...       ...          ...             ...
13490  54337200  8720390921  2020-12-31   20000.0           12             NaN
13491  59931360  8718580146  2020-12-31  100000.0           12             NaN
13492  46156488  8717515352  2020-12-31   20000.0           12             NaN
13493  35858614  8716668316  2020-12-31   10000.0           12             NaN
13494  49335467  8710511927  2020-12-31   10000.0           12             NaN

[13495 rows x 6 columns]

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Merchant_name  5 non-null      object
 1   Merchant_id    5 non-null      int64
 2   Rate_pct       5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13428 entries, 0 to 13427
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User_id          13428 non-null  int64
 1   First_tran_date  13428 non-null  object
 2   Location         13428 non-null  object
 3   Age              13428 non-null  object
 4   Gender           13428 non-null  object
dtypes: int64(1), object(4)
memory usage: 524.7+ KB

In [ ]:
def convert_date(date):
    try:
        converted_date = pd.to_datetime(date, format='mixed', dayfirst=True)
        if converted_date.year > 2100:
            return None
        return converted_date
    except ValueError:
        return None

df3['First_tran_date'] = df3['First_tran_date'].apply(convert_date)

df3 = df3.dropna(subset=['First_tran_date'])

df3['First_tran_date'] = df3['First_tran_date'].dt.strftime('%Y-%m-%d')

print(df3)

        User_id First_tran_date      Location       Age  Gender
0      41654498      2018-05-02          HCMC  33_to_37    MALE
1      51276281      2019-12-08  Other Cities   unknown    MALE
2      49152375      2019-12-20  Other Cities  23_to_27    MALE
3       5971050      2019-08-01          HCMC  28_to_32    MALE
4      48134464      2019-08-23  Other Cities  18_to_22  FEMALE
...         ...             ...           ...       ...     ...
13423  39810630      2018-03-19  Other Cities  28_to_32     Nam
13424  47628375      2019-09-05          HCMC  28_to_32  female
13425  46334970      2019-04-23  Other Cities   unknown    male
13426  50760533      2019-11-13  Other Cities  18_to_22      Ná»¯
13427  44818205      2019-03-05          HCMC  18_to_22     Nam

[13354 rows x 5 columns]

In [ ]:
df1.describe().T

,count,mean,std,min,25%,50%,75%,max
user_id,13495.0,4.021140e+07,1.368218e+07,1.138060e+05,3.597480e+07,4.346840e+07,4.940701e+07,6.143328e+07
order_id,13495.0,6.385662e+09,1.289348e+09,4.166563e+09,5.303238e+09,6.274443e+09,7.502845e+09,8.723876e+09
Amount,13495.0,5.147123e+04,7.331535e+04,1.000000e+04,2.000000e+04,3.000000e+04,5.000000e+04,2.500000e+06
Merchant_id,13495.0,1.276102e+01,8.945555e-01,1.200000e+01,1.200000e+01,1.200000e+01,1.300000e+01,1.600000e+01

In [ ]:
df2.describe().T

             count  mean       std   min   25%   50%   75%   max
Merchant_id    5.0  14.0  1.581139  12.0  13.0  14.0  15.0  16.0
Rate_pct       5.0   3.4  0.894427   2.0   3.0   4.0   4.0   4.0

In [ ]:
df3.describe().T

,count,mean,std,min,25%,50%,75%,max
User_id,13354.0,4.022602e+07,1.370766e+07,113806.0,35933963.75,43530636.5,49459252.25,61433285.0

In [ ]:
df1.isna().sum()

user_id                0
order_id               0
Date                   0
Amount                 0
Merchant_id            0
Purchase_status    11260
dtype: int64

In [ ]:
df1["Purchase_status"].value_counts()

Purchase_status
Mua há»    2235
Name: count, dtype: int64

In [ ]:
df1.duplicated().sum()

0

In [ ]:
df1.nunique()

user_id            13390
order_id           13495
Date                 366
Amount                16
Merchant_id            5
Purchase_status        1
dtype: int64

In [ ]:
df3.isna().sum()

User_id            0
First_tran_date    0
Location           0
Age                0
Gender             0
dtype: int64

In [ ]:
df3.duplicated().sum()

0

In [ ]:
df3.nunique()

User_id            13316
First_tran_date     1528
Location               6
Age                    6
Gender                 8
dtype: int64

In [ ]:
print(df3.Location.value_counts())
print('*' * 100)
print(df3.Age.value_counts())
print('*' * 100)
print(df3.Gender.value_counts())

Location
Other Cities        5997
HCMC                4084
HN                  1426
Other               1026
Unknown              758
Ho Chi Minh City      63
Name: count, dtype: int64
****************************************************************************************************
Age
23_to_27    3401
28_to_32    2777
unknown     2509
33_to_37    1735
18_to_22    1688
>37         1244
Name: count, dtype: int64
****************************************************************************************************
Gender
MALE      6242
FEMALE    3390
Nam       1362
Ná»¯        1246
female     896
M           92
male        71
f           55
Name: count, dtype: int64

In [ ]:
df3['Location'] = df3['Location'].replace({'Other':'Other Cities','Ho Chi Minh City':'HCMC'})
df3['Gender'] = df3['Gender'].replace({'Nam':'MALE','Ná»¯':'FEMALE','male':'MALE','female':'FEMALE','M':'MALE','f':'FEMALE'})
print(df3.Gender.value_counts())
print('*' * 100)
print(df3.Location.value_counts())

Gender
MALE      7767
FEMALE    5587
Name: count, dtype: int64
****************************************************************************************************
Location
Other Cities    7023
HCMC            4147
HN              1426
Unknown          758
Name: count, dtype: int64

In [ ]:
df1.sample(5)

        user_id    order_id        Date   Amount  Merchant_id Purchase_status
5922   55293364  6028683627  2020-06-22  30000.0           13          Mua há»
1124   34006698  4628074358  2020-02-05  20000.0           13             NaN
3177   51189548  5252882521  2020-04-04  20000.0           13             NaN
13380  15696938  8696452205  2020-12-30  10000.0           13          Mua há»
17     15602866  4172907480  2020-01-01  50000.0           13             NaN

In [ ]:
df3.sample(5)

       User_id First_tran_date      Location       Age  Gender
3297  55520490      2020-10-17  Other Cities   unknown  FEMALE
3601  50178876      2019-10-24  Other Cities  23_to_27  FEMALE
1102  55634697      2020-06-18  Other Cities  18_to_22    MALE
3604  44591867      2019-12-26  Other Cities  23_to_27    MALE
4003  43987352      2018-10-28          HCMC  23_to_27    MALE

In [ ]:
merged_df = pd.merge(df1, df2[['Merchant_id', 'Rate_pct']], on='Merchant_id', how='left')
merged_df["Revenue"] = merged_df.Amount * (merged_df.Rate_pct / 100)
merged_df

,user_id,order_id,Date,Amount,Merchant_id,Purchase_status,Rate_pct,Revenue
0,21269588,4169517626,2020-01-01,10000.0,13,NaN,3,300.0
1,28097592,4170276686,2020-01-01,20000.0,13,NaN,3,600.0
2,47435144,4166729310,2020-01-01,10000.0,12,NaN,2,200.0
3,29080935,4174460303,2020-01-01,10000.0,13,NaN,3,300.0
4,14591075,4168216749,2020-01-01,10000.0,12,NaN,2,200.0
...,...,...,...,...,...,...,...,...
13490,54337200,8720390921,2020-12-31,20000.0,12,NaN,2,400.0
13491,59931360,8718580146,2020-12-31,100000.0,12,NaN,2,2000.0
13492,46156488,8717515352,2020-12-31,20000.0,12,NaN,2,400.0
13493,35858614,8716668316,2020-12-31,10000.0,12,NaN,2,200.0
13494,49335467,8710511927,2020-12-31,10000.0,12,NaN,2,200.0

## Using data from the 'Commission' table, add a column 'Revenue' in the 'Transactions' table that displays MoMo's earned revenue for each order

In [ ]:
df1["Revenue"] = merged_df["Revenue"]

In [ ]:
df1

,user_id,order_id,Date,Amount,Merchant_id,Purchase_status,Revenue
0,21269588,4169517626,2020-01-01,10000.0,13,NaN,300.0
1,28097592,4170276686,2020-01-01,20000.0,13,NaN,600.0
2,47435144,4166729310,2020-01-01,10000.0,12,NaN,200.0
3,29080935,4174460303,2020-01-01,10000.0,13,NaN,300.0
4,14591075,4168216749,2020-01-01,10000.0,12,NaN,200.0
...,...,...,...,...,...,...,...
13490,54337200,8720390921,2020-12-31,20000.0,12,NaN,400.0
13491,59931360,8718580146,2020-12-31,100000.0,12,NaN,2000.0
13492,46156488,8717515352,2020-12-31,20000.0,12,NaN,400.0
13493,35858614,8716668316,2020-12-31,10000.0,12,NaN,200.0
13494,49335467,8710511927,2020-12-31,10000.0,12,NaN,200.0

##Combined with the 'User_Info' table, add columns: Age, Gender, Location, Type_user (New/Current) in 'Transactions' table

In [ ]:
warnings.filterwarnings("ignore")
df3.rename(columns={'User_id': 'user_id'}, inplace=True)
df1 = pd.merge(df1, df3[['user_id', 'Age', 'Gender', 'Location', 'First_tran_date']], on='user_id', how='left')

df1

,user_id,order_id,Date,Amount,Merchant_id,Purchase_status,Revenue,Age,Gender,Location,First_tran_date
0,21269588,4169517626,2020-01-01,10000.0,13,NaN,300.0,>37,FEMALE,HN,2018-12-11
1,28097592,4170276686,2020-01-01,20000.0,13,NaN,600.0,>37,FEMALE,HN,2019-12-30
2,47435144,4166729310,2020-01-01,10000.0,12,NaN,200.0,18_to_22,FEMALE,HN,2019-11-11
3,29080935,4174460303,2020-01-01,10000.0,13,NaN,300.0,18_to_22,FEMALE,HN,2019-10-24
4,14591075,4168216749,2020-01-01,10000.0,12,NaN,200.0,18_to_22,FEMALE,Other Cities,2019-12-28
...,...,...,...,...,...,...,...,...,...,...,...
13571,54337200,8720390921,2020-12-31,20000.0,12,NaN,400.0,unknown,MALE,Other Cities,2020-11-17
13572,59931360,8718580146,2020-12-31,100000.0,12,NaN,2000.0,unknown,FEMALE,Other Cities,2020-11-09
13573,46156488,8717515352,2020-12-31,20000.0,12,NaN,400.0,23_to_27,FEMALE,Other Cities,2019-11-01
13574,35858614,8716668316,2020-12-31,10000.0,12,NaN,200.0,28_to_32,FEMALE,HN,2019-11-04
13575,49335467,8710511927,2020-12-31,10000.0,12,NaN,200.0,unknown,MALE,Other Cities,2019-09-15

In [ ]:
df1['Date'] = pd.to_datetime(df1['Date'])

In [ ]:
df1['First_tran_date'] = pd.to_datetime(df1['First_tran_date'])

In [ ]:
df1['Type_user'] = df1.apply(lambda row: 'New' if (row['Date'].year == row['First_tran_date'].year) and (row['Date'].month == row['First_tran_date'].month) else 'Current', axis=1)
df1

,user_id,order_id,Date,Amount,Merchant_id,Purchase_status,Revenue,Age,Gender,Location,First_tran_date,Type_user
0,21269588,4169517626,2020-01-01,10000.0,13,NaN,300.0,>37,FEMALE,HN,2018-12-11,Current
1,28097592,4170276686,2020-01-01,20000.0,13,NaN,600.0,>37,FEMALE,HN,2019-12-30,Current
2,47435144,4166729310,2020-01-01,10000.0,12,NaN,200.0,18_to_22,FEMALE,HN,2019-11-11,Current
3,29080935,4174460303,2020-01-01,10000.0,13,NaN,300.0,18_to_22,FEMALE,HN,2019-10-24,Current
4,14591075,4168216749,2020-01-01,10000.0,12,NaN,200.0,18_to_22,FEMALE,Other Cities,2019-12-28,Current
...,...,...,...,...,...,...,...,...,...,...,...,...
13571,54337200,8720390921,2020-12-31,20000.0,12,NaN,400.0,unknown,MALE,Other Cities,2020-11-17,Current
13572,59931360,8718580146,2020-12-31,100000.0,12,NaN,2000.0,unknown,FEMALE,Other Cities,2020-11-09,Current
13573,46156488,8717515352,2020-12-31,20000.0,12,NaN,400.0,23_to_27,FEMALE,Other Cities,2019-11-01,Current
13574,35858614,8716668316,2020-12-31,10000.0,12,NaN,200.0,28_to_32,FEMALE,HN,2019-11-04,Current
13575,49335467,8710511927,2020-12-31,10000.0,12,NaN,200.0,unknown,MALE,Other Cities,2019-09-15,Current

In [ ]:
with pd.ExcelWriter('MoMo_Clean.xlsx') as writer:
    df1.to_excel(writer, sheet_name='Data Transactions', index=False)
    df2.to_excel(writer, sheet_name='Data Commission', index=False)
    df3.to_excel(writer, sheet_name='Data User_Info',  index=False)